version: '3.6'

services:
  chatgpt:
    build: 
      context: .
      args:
        DEFAULT_MODEL: ${DEFAULT_MODEL}
        NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT: ${NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    ports:
      - 3000:3000
    restart: always
    env_file: .env.local

